# å¯¼èˆªé…ç½®æ–‡ä»¶
# åˆ†ç±»å¯¼èˆªé“¾æ¥

categories:
  - name: å¼€å‘å·¥å…·
    icon: code
    links:
      - name: GitLab
        url: https://git.qivators.com/
        description: ç§æœ‰ä»£ç æ‰˜ç®¡å¹³å°
        icon: figma
      - name: Outline
        url: https://docs.ly7799.com
        description: ä»»åŠ¡,wiki,bugç­‰...
        icon: browser
      - name: GitHub
        url: https://github.com/QuantumInnovators
        description: githubç»„ç»‡-QuantumInnovators
        icon: github
      - name: Vaultwarden 
        url: https://bw.qivators.com/
        description: å¯†ç ç®¡ç†
        icon: vaultwarden
      - name: AI-Agent
        url: https://ai.ly7799.com/
        description: AIè‡ªåŠ¨éƒ¨ç½²è¿ç»´å¹³å°
        icon: gamepad
      - name: Dify
        url: https://dify.qivators.com
        description: Dify å¹³å°ï¼Œè‡ªå»ºå·¥ä½œæµ
        icon: image

  - name: æ–‡æ¡£èµ„æº
    icon: doc
    links:
      - name: ç»¿è”äº‘
        url: https://ug.link/ly7799
        description: NAS-å­˜æ”¾æ‰€æœ‰é¡¹ç›®å†…å®¹
        icon: image
      - name: å›¢é˜Ÿä»‹ç»
        url: https://qivators.com
        description: å›¢é˜Ÿä»‹ç»ï¼Œå›¢é˜Ÿåšå®¢ï¼Œå›¢é˜Ÿæˆæœå±•ç°
        icon: image
      - name: MinIO -å­˜å‚¨
        url: https://file-admin.ly7799.com/dashboard
        description: é«˜æ€§èƒ½é«˜å¯ç”¨çš„æ–‡ä»¶ç³»ç»ŸæœåŠ¡
        icon: image
  
  - name: å­¦ä¹ èµ„æº
    icon: book
    links:
      - name: å›¾ä¹¦é¦†
        url: https://book.qivators.com/
        description: ğŸ“š ç”¨äºæµè§ˆã€é˜…è¯»å’Œä¸‹è½½å­˜å‚¨åœ¨ Calibre æ•°æ®åº“ä¸­çš„ç”µå­ä¹¦çš„ Web åº”ç”¨ç¨‹åº
        icon: book